# Generated by Django 4.1 on 2022-08-29 01:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(upload_to='')),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Short description')),
                ('level', models.IntegerField()),
                ('full_acces', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=250)),
                ('vbucks', models.IntegerField()),
                ('bling_amount', models.IntegerField()),
                ('gliders_amount', models.IntegerField()),
                ('save_world', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=250)),
                ('hot_og', models.CharField(max_length=250)),
                ('platform', models.CharField(max_length=250, verbose_name='PC, PS, Xbox...')),
                ('mail', models.CharField(choices=[('Connected', 'Email in pack'), ('No email', 'No email'), ('Others', 'Other')], max_length=250, verbose_name='Type of email on account')),
                ('outfits', models.IntegerField()),
                ('emotions', models.IntegerField()),
                ('description', models.TextField(verbose_name='Full account description')),
                ('acc_raiting', models.CharField(default='5*', max_length=20)),
                ('acc_price', models.IntegerField(default=10)),
                ('date_post', models.DateField(default=datetime.datetime(2022, 8, 29, 1, 1, 17, 584872))),
            ],
            options={
                'ordering': ('-outfits',),
            },
        ),
        migrations.CreateModel(
            name='PostsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='shop/account_images/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.account')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
