# Generated by Django 4.1 on 2022-09-19 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 1, 58, 7, 491839)),
        ),
    ]
