# Generated by Django 4.1 on 2022-09-02 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('account_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2022, 9, 2, 2, 27, 39, 439842)),
        ),
    ]
