# Generated by Django 4.1 on 2022-09-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_account_views_alter_account_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
